title: Keyur08
logo:"/Profile.png"
description: >
  <br>
 AI Student
  <br>
  <a href="https://www.linkedin.com/in/keyur-jain-469857228/">
    <img src="https://img.shields.io/badge/linkedin-%230077B5.svg?&style=for-the-badge&logo=linkedin&logoColor=white">
  </a>
  <a href="mailto:keyurjain9913@gmail.com">
    <img alt="Gmail" src="https://img.shields.io/badge/Gmail-D14836?style=for-the-badge&logo=gmail&logoColor=white" />
  </a>
theme: jekyll-theme-minimal
