title: Keyur Jain
logo: "/Profile.png"
description: >
  <br>
  AI/ML | Web-3 Enthusiast
  <br>
  <a href="https://www.linkedin.com/in/keyur-jain-469857228/">
    <img src="https://img.shields.io/badge/linkedin-%230077B5.svg?&style=for-the-badge&logo=linkedin&logoColor=white">
  </a>
  <a href="mailto:keyurjain9913@gmail.com">
    <img alt="Gmail" src="https://img.shields.io/badge/Gmail-D14836?style=for-the-badge&logo=gmail&logoColor=white" />
  </a>
  <a href="https://twitter.com/KeyurJain_2208" target="_blank">
    <img alt="Twitter" src="https://img.shields.io/twitter/url?style=for-the-badge&logo=gmail&logoColor=white"/>
    </a>
    
theme: jekyll-theme-minimal
